title: "Ashmore Arboretum Plants"
description: "Plant listings for Ashmore Arboretum"

# For a user/organization site root (https://ashmorearboretum.github.io/), use an empty baseurl:
baseurl: ""
url: "https://ashmorearboretum.github.io"

markdown: kramdown
permalink: pretty

collections:
  plants:
    output: true
    permalink: /plants/:name/

defaults:
  - scope:
      path: ""
      type: "plants"
    values:
      layout: "plant"

exclude:
  - node_modules
  - vendor/bundle
