title: "" # This shows in browser tab; can be anything
# theme: jekyll-theme-architect
show_downloads: false   # Hides download buttons if present
# logo: /Ashmore-Arboretum-Banner.JPG   # Or /assets/img/logo.png
collections:
  plants:
    output: true
    permalink: /plants/:slug/  # :slug lowercases and hyphens title

debug: true

test3
