title: "Ashmore Arboretum Plants"
description: "Plant listings for Ashmore Arboretum"
# Set baseurl to "/AshmoreArboretumPlants" if you publish at
# https://ashmorearboretum.github.io/AshmoreArboretumPlants
baseurl: "/AshmoreArboretumPlants"
url: "https://ashmorearboretum.github.io"

markdown: kramdown
permalink: pretty

collections:
  plants:
    output: true
    permalink: /plants/:name/

defaults:
  - scope:
      path: ""
      type: "plants"
    values:
      layout: "plant"

# Exclude node / build artifacts (optional)
exclude:
  - node_modules
  - vendor/bundle
