title: "" # This shows in browser tab; can be anything
theme: jekyll-theme-architect
show_downloads: false   # Hides download buttons if present
logo: /Ashmore_Arboretum_Hrz.png   # Or /assets/img/logo.png
