title: "" # This shows in browser tab; can be anything
# theme: jekyll-theme-architect
show_downloads: false   # Hides download buttons if present
# logo: /Ashmore-Arboretum-Banner.JPG   # Or /assets/img/logo.png
collections:
  plants:
    output: true  # Makes each plant page live
    permalink: /plants/:title/  # URL like /plants/adiantum-hispidulum/
